const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const crypto = require("crypto");

const userSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true, unique: true },
    fullName: { type: String, required: true },
    email: { type: String, required: true, unique: true, lowercase: true },
    mobile: { type: String, required: true },
    role: {
      type: String,
      enum: ["Admin", "Employee"], // User model is only for Admin and Employee
      required: true,
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
    },
    subcategory: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SubCategory",
    },
    status: {
      type: String,
      enum: ["Active", "Inactive"],
      default: "Active",
    },
    verificationStatus: {
      type: String,
      enum: ["Approved", "Pending", "Rejected", "Blocked"],
      default: "Pending",
    },

    profileImage: { type: String, default: "" },

    lastLogin: { type: Date },

    // Password Fields
    passwordHash: { type: String },
    autoGeneratedPassword: { type: Boolean, default: false },

    // OTP Fields
    otp: { type: String },
    otpExpires: { type: Date },

  },
  {
    timestamps: { createdAt: true, updatedAt: "updatedAt" },
  }
);

// Hash password before saving
userSchema.pre("save", async function (next) {
  if (!this.isModified("passwordHash")) return next();
  if (this.passwordHash) {
    this.passwordHash = await bcrypt.hash(this.passwordHash, 10);
  }
  next();
});

// Compare password method
userSchema.methods.comparePassword = async function (candidatePassword) {
  if (!this.passwordHash) {
    return false;
  }
  return await bcrypt.compare(candidatePassword, this.passwordHash);
};

// Generate JWT token
userSchema.methods.generateAuthToken = function () {
  return jwt.sign(
    { id: this._id, email: this.email, role: this.role },
    process.env.JWT_SECRET,
    {
      expiresIn: process.env.JWT_EXPIRES_IN || "24h",
    }
  );
};


module.exports = mongoose.model("User", userSchema);
