// User roles
const ROLES = {
  ADMIN: "Admin",
  EMPLOYEE: "Employee",
  CONSULTANT: "Consultant",
  CLIENT: "Client",
};

// Role hierarchy - higher number = more permissions
const ROLE_HIERARCHY = {
  [ROLES.CLIENT]: 1,
  [ROLES.CONSULTANT]: 2,
  [ROLES.EMPLOYEE]: 3,
  [ROLES.ADMIN]: 4,
};

// Permissions mapping
const PERMISSIONS = {
  // User Management
  CREATE_USER: [ROLES.ADMIN],
  READ_USERS: [ROLES.ADMIN, ROLES.CONSULTANT],
  UPDATE_USER: [ROLES.ADMIN],
  DELETE_USER: [ROLES.ADMIN],

  // Consultation Management
  CREATE_CONSULTATION: [ROLES.ADMIN, ROLES.CONSULTANT],
  READ_CONSULTATIONS: [ROLES.ADMIN, ROLES.CONSULTANT, ROLES.CLIENT],
  UPDATE_CONSULTATION: [ROLES.ADMIN, ROLES.CONSULTANT],
  DELETE_CONSULTATION: [ROLES.ADMIN],

  // Category Management
  CREATE_CATEGORY: [ROLES.ADMIN],
  READ_CATEGORIES: [ROLES.ADMIN, ROLES.CONSULTANT, ROLES.CLIENT],
  UPDATE_CATEGORY: [ROLES.ADMIN],
  DELETE_CATEGORY: [ROLES.ADMIN],

  // Profile Management
  UPDATE_OWN_PROFILE: [ROLES.ADMIN, ROLES.CONSULTANT, ROLES.CLIENT],

  // Reports
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.CONSULTANT],
  EXPORT_REPORTS: [ROLES.ADMIN],
};

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSIONS,
};
